[workspace]
resolver = "2"
members = [
    "tunelling",
    "get-location",
    "ui-extract-audio",
    "ui-system-stats",
    "lib-wifi-ssid",
    "video-recorder-for-mum",
    "ui-bmi-for-dummies",
    "wasm-command",
    "fahrenheit_to_celsius", "fahrenheit_to_celsius_wasm", "fahrenheit_to_celsius_egui"]
