[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
yew = { version = "0.20", features = ["csr"] }
wasm-bindgen = "0.2"
web-sys = "0.3.72"
wasm-bindgen-futures = "0.4.45"
serde_json = "1.0.128"
gloo-net = "0.3"