[package]
name = "video-recorder-for-mum"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.22.0"
egui-winit = "0.22.0"
eframe = "0.22.0"
chrono = "0.4.38"


[[bin]]
name = "main"
path = "src/bin/main.rs"


[[bin]]
name = "recordingcli"
path = "src/bin/recordingcli.rs"


[[bin]]
name = "hello"
path = "src/bin/hello.rs"
