[package]
name = "excel_to_csv"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.23.1"         # Or the latest version
indicatif = "0.17.8"
clap = { version = "4.5.20", features = ["derive"] }